### ISSUE TITLE
Broken image links in 3.3. Properties of natural signals

### ISSUE THREAD

**Issue by feedthebeat90** [Atcold/pytorch-Deep-Learning#103]
The following image links  are broken:

- [x] Figure 2(a)
- [x] Figure 2(b)
- [x] Figure 3(a)
- [x] Figure 3(b)

See https://atcold.github.io/pytorch-Deep-Learning/en/week03/03-3/

I think the images were originally obtained from this presentation:
[02 - CNN.pdf](https://github.com/Atcold/pytorch-Deep-Learning/files/4300668/02.-.CNN.pdf)

See pages 10-11

-----------------------------------------------

Also, small suggestions:

- [x] Change Figure 4 to include R^7 and R^2 as in Slide 20 . 
This would better match the text for Figure 4.

- [x] Include Figure (4b maybe?) with that on Slide 21 to show what Padding is doing

**Comment by ebetica** [comment]
The images should be displaying now. I'll defer to @Atcold for the content suggestions, maybe you can make PR with these suggestions :)

**Comment by Atcold** [comment]
@feedthebeat90, sounds like a solid improvement.
Can you send a PR with these augmentations?

**Comment by feedthebeat90** [comment]
Sure, I think I should only add these lines below, however I do not have privileges to upload the images to the "..\images\" folder

```

<center><img src="{{site.baseurl}}/images/week03/03-3/Figure_4a_kernels_on_1D_data.png" width="350px" /><br>
<b>Figure 4(a):</b> Kernels on 1D Data</center>

<center><img src="{{site.baseurl}}/images/week03/03-3/Figure_4b_zero_padding.png" width="350px" /><br>
<b>Figure 4(b):</b> Data with Zero Padding</center>


```
So I'll leave them here

<img width="652" alt="Figure_4a_kernels_ on_1D_data" src="https://user-images.githubusercontent.com/36459629/76262127-e9950b00-6231-11ea-979d-2cc744c2c8bb.png">
<img width="817" alt="Figure_4b_zero_padding" src="https://user-images.githubusercontent.com/36459629/76262128-e9950b00-6231-11ea-8bfc-eb61466cfc63.png">

**Comment by ebetica** [comment]
It would be great if you can follow GitHub's workflow to officially recommend changes! These graphics look great. Here's a [guide](https://gist.github.com/Chaser324/ce0505fbed06b947d962) on how to do this - you'll want to eventually open a Pull Request with these changes, that we can just merge with one click.

**Comment by Atcold** [comment]
@feedthebeat90, can you please send a PR?

**Comment by feedthebeat90** [comment]
Done @ebetica @Atcold 

A few comments:

Please check if the formatting for markdown looks good on the website. I cannot correctly preview changes from browser with the Preview Button.

Also, move images 4(a) and 4(b) to the repo "./images/" folder , I don 't have privileges to do that (to the best of my knowledge), so I've used random URLs that Github generated to store images.

Sorry for the delay, I've been our for the last few days!

**Comment by Atcold** [comment]
@feedthebeat90, you just need to place those images in the correct location.
Start by forking the current repo.
Add the images in the right location.
`git add <my_new_files> && git commit -m 'whatever'  && git push`
Then you do a pull request.
Use the same syntax shown [here](https://atcold.github.io/pytorch-Deep-Learning/en/about/) for inserting images.

Let me know if you need any further instruction.

**Comment by feedthebeat90** [comment]
Cool , I was not aware I could add files through forking + push + PR , my bad ! 😅 

I tried a second time  😸

**Comment by Atcold** [comment]
I'm not aware how you can add files in any alternative way 😳

**Comment by feedthebeat90** [comment]
> I'm not aware how you can add files in any alternative way 😳

Just by simple push or through web app upload but only if you are the owner ( I was working with a clone of your repo) , lol  😝

**Comment by Atcold** [comment]
Hehe, nah, I prefer the terminal :)
