### ISSUE TITLE
Weird tab name

### ISSUE THREAD

**Issue by Atcold** [Atcold/pytorch-Deep-Learning#134]
Where are these coming from, @ebetica? Can we avoid the repetition and leave there just the capital instance? Also, where is the Korean edition getting the DL from? I didn't input that anywhere, I think.

<img width="248" alt="Screenshot 2020-03-23 01 56 28" src="https://user-images.githubusercontent.com/2119355/77287419-eaa34f00-6cab-11ea-8eb3-924d23c76e43.png">

<img width="246" alt="Screenshot 2020-03-23 02 14 34" src="https://user-images.githubusercontent.com/2119355/77287469-0b6ba480-6cac-11ea-9b9f-45353d370698.png">

<img width="250" alt="Screenshot 2020-03-23 01 56 53" src="https://user-images.githubusercontent.com/2119355/77287427-eecf6c80-6cab-11ea-952b-a84f2392eda5.png">

**Comment by ebetica** [comment]
The first is always the title of the page, and the second is always the title of the book according to the config file: https://github.com/Atcold/pytorch-Deep-Learning/blob/master/docs/_config.yml#L4

There's a different title in each language.

**Comment by Atcold** [comment]
Oh…
Also, now the Korean fixed itself, LOL. Whatever…
<img width="176" alt="Screenshot 2020-03-25 02 13 13" src="https://user-images.githubusercontent.com/2119355/77507182-40a7fc00-6e3e-11ea-9f73-c6f8e05b98c1.png">
