### ISSUE TITLE
Week 7 SSL, EBM with details and examples contains the 3 questions

### ISSUE THREAD

**Issue by shr264** [Atcold/pytorch-Deep-Learning#137]
Hi @Atcold,

I just noticed that in week 7, section 2 (SSL, EBM with details and examples) the questions also got included when the notes got posted:
https://atcold.github.io/pytorch-Deep-Learning/en/week07/07-2/

These are right at the bottom of the page.I am not sure if this was intentional to leave them in as this is not the case in any other section. These refer to the three questions and answers we are asked to provide along with our weekly notes. I apologize for this confusion, but I had left this in as a comment along with my notes, but perhaps these should not be here.

Best,
Syed

**Comment by Atcold** [comment]
Can you plz take them off?
Thanks.

**Comment by shr264** [comment]
just made the change. Note sure where to share the questions, but I'll put them on here:

1. What are some advantages of latent variable EBMs?
A. The main advantage of Latent variable models is that they allow multiple predictions through the latent variable.
2. Is K-means an architectural or a contrastive method?
A. Architectural as all we do is push the energy down in certain regions
3. Where do Denoising AEs work well? Give one example of a masked AE?
A. NLP. BERT.

**Comment by Atcold** [comment]
They should go in the spreadsheet.
