### ISSUE TITLE
[All Langs] ALL links broken on index.md

### ISSUE THREAD

**Issue by LecJackS** [Atcold/pytorch-Deep-Learning#259]
As Mauri commented in the Spanish slack channel, **ALL** links are broken on index.md, as they point to `.../es/es/...` instead of `.../es/...`

Eg:

> `https://atcold.github.io/pytorch-Deep-Learning/es/es/week01/01-1`

Index md shows only one `es/`

> `<td><a href="es/week01/01-1">Historia y motivación</a></td>`

Not sure if we should remove it (as it would point at the main file in english) or some other action is needed.

Other langs seems to have this problem too.

**Comment by Atcold** [comment]
@ebetica, please, look into this issue.
Thanks @LecJackS for spotting the problem!

**Comment by ebetica** [comment]
I think this has been fixed as of #263 ? It works now afaik.
