### ISSUE TITLE
[EN] Possible missing image on Week 6 - Part 3

### ISSUE THREAD

**Issue by LecJackS** [Atcold/pytorch-Deep-Learning#261]
Just [after figure 4 of Vec to Seq](https://atcold.github.io/pytorch-Deep-Learning/en/week06/06-3/), diagram there is this paragraph saying:

> Some of the results of this network **are shown below**. For example, in the first column the description regarding the last picture is “A herd of elephants walking across a dry grass field.”, which is very well refined. Then in the second column, the first image outputs “Two dogs play in the grass.”, while it’s actually three dogs. In the last column are the more wrong examples such as “A yellow school bus parked in a parking lot.”

But below that paragraph, there is no image with those examples, as it is actually [shown in the Practicum video, at 4:41](https://youtu.be/8cAffg2jaT0?t=281)

**Comment by LecJackS** [comment]
Also missing **_seq to vec to seq_** diagram image

> You start with a sequence of symbols here shown in pink. Then everything gets condensed into this final h, which represents a concept.

**Comment by LecJackS** [comment]
Similar **_seq to seq_**
> One cool example is this RNN-writer. When you start typing "the rings of Saturn glittered while", it suggests the following "two men looked at each other".

**Comment by Atcold** [comment]
Contacting the authors.
Thanks!

**Comment by Atcold** [comment]
Fixed in #308.
