### ISSUE TITLE
15-Transformer Notebook: Encoder Class Possibly Using Only Last Layer

### ISSUE THREAD

**Issue by beelze-b** [Atcold/pytorch-Deep-Learning#270]
Hi,

I was watching the recording of the lecture and you mentioned that you can stack the encoder layers.

I was looking at the forward pass of the Encoder class, and it seems to overwrite x in each part of the for loop, so it seems to me that it only returns the final layer's encoding of the embedding.

Am I missing something? It doesn't seem that the previous EncoderLayer's encodings are being used. I can submit a PR with my understanding of the fix if this is an actually an issue.

**Comment by Atcold** [comment]
LOL, you're talking about this?

```python
def forward(self, x):
        embedding = self.embedding(x) # Transform to (batch_size, input_seq_length, d_model)

        for i in range(self.num_layers):
            x = self.enc_layers[i](embedding)

        return x  # (batch_size, input_seq_len, d_model)
```

**Comment by beelze-b** [comment]
Yes, I was, and I was wondering if the fix could looking something like this?

```
def forward(self, x):
    embedding = self.embedding(x) # Transform to (batch_size, input_seq_length, d_model)

    for i in range(self.num_layers):
        embedding = self.enc_layers[i](embedding)

    return embedding  # (batch_size, input_seq_len, d_model)
```

If so, I could do a PR after the fix, re-running the notebook, and re-heating some lasagna.

Pinging @ashkamath to see if that is acceptable.

**Comment by ashkamath** [comment]
@beelze-b. Yup that would fix it :) Thanks for spotting the bug!
