### ISSUE TITLE
Korean translation is on the English website.

### ISSUE THREAD

**Issue by JonathanSum** [Atcold/pytorch-Deep-Learning#272]
![image](https://user-images.githubusercontent.com/21982975/80301563-b7942580-8759-11ea-871a-d425f82a7c42.png)

**Comment by Atcold** [comment]
Hahahahahahahahahahah 🤣🤣🤣
@skyil7, what's going on??????

**Comment by skyil7** [comment]
What the... Now It's on español 🤣🤣
![image](https://user-images.githubusercontent.com/30472421/80452771-e8df4200-8961-11ea-906e-606f465900d8.png)

**Comment by skyil7** [comment]
Both of them are translation of `1.1 Motivation of DL ~~`.
I think there is some problem with `_config.yaml`

**Comment by Atcold** [comment]
Yes, there's no chapter `11`. Students forgot to submit.
I think it'll fix itself when I'm merging their contribution.
