### ISSUE TITLE
Contributors page?

### ISSUE THREAD

**Issue by charlesoblack** [Atcold/pytorch-Deep-Learning#334]
Given that all the scribes contributed to this website, should we maybe have a "contributors" page? I imagine even just linking their NYU emails would be fine.

**Comment by ebetica** [comment]
Does #336 make you happy? I imagine you can go back and add a link to your email in the authors line if you like. (`<a href="mailto:charlesoblack@nyu.edu">charlesoblack</a>`)

**Comment by charlesoblack** [comment]
Indeed it does. Thank you!

**Comment by JonathanSum** [comment]
I just try to make a comment here and hope no one will see it. 

Only For me, I don't really need to have a contributor page that shows, "Oh, I did this".
I hope after this course, I can build an **successful** energy-based model or someone more advanced than LSTM. 

This is what I want. And this really makes me feel happy than that contributor page.

**Comment by charlesoblack** [comment]
It's not really about being able to say "i did this", it's about following
proper scientific practice and not plagiarizing/stealing someone else's
work.

**Comment by Atcold** [comment]
Yes, of course! It's absolutely important to enforce traceability!
Thank you for rising this issue, which I believe now has been resolved.
