### ISSUE TITLE
Possible English error?

### ISSUE THREAD

**Issue by JonathanSum** [Atcold/pytorch-Deep-Learning#353]
Energy-based models that have a regulariser, which is additive to your energy function, are completely equivalent to Bayesian models where the likelihood is exponential of the energy, and now you get exp(energy) exp(regularizer),

-for the word "regulariser", is this a typo?  I see regulariser and regularizer.

![image](https://user-images.githubusercontent.com/21982975/84686128-46b6f180-aef0-11ea-86d7-c5bd8a4f899c.png)

**Comment by Atcold** [comment]
Yes, let's use *regulariser* with an *s*. Can you send a PR?
