### ISSUE TITLE
Possible Week09 Part3  Error in math notation and english spelling

### ISSUE THREAD

**Issue by JonathanSum** [Atcold/pytorch-Deep-Learning#356]
![image](https://user-images.githubusercontent.com/21982975/84769162-40755380-af8a-11ea-8e2d-ea693ddf97bd.png)
Does it mean C(G(z)) goes to m or 0, or this is just an error? 

Another one:
I think it means "pass the point" rather than "past the point".
This poses a problem for convergence of the GAN: the discriminator feedback gets less meaningful over time. If the GAN continues training **past the point** when the discriminator is giving completely random feedback, then the generator starts to train on junk feedback and its quality may collapse. [Refer to training convergence in GANs]

Another one:
Week 7 part2:
As z over a set, y varies over the manifold of possible predictions.
Should it be:
**As z varies over a set,** y varies over the manifold of possible predictions.?

**Comment by Atcold** [comment]
1. The parameters of `C` are adapted such that `C(G(z)) -> m`, the parameters of `G` are adapted such that `C(G(z)) -> 0`.
2. *Train past the point* is correct. It means "train further the event in which".
3. Yes, that's a valid correction.
