### ISSUE TITLE
[EN]I guess this is not leaking relu?

### ISSUE THREAD

**Issue by JonathanSum** [Atcold/pytorch-Deep-Learning#399]
![image](https://user-images.githubusercontent.com/21982975/86534482-a10ef680-be8d-11ea-8317-b2dee2a56d1f.png)

Please don't laugh at me if I am wrong.

**Comment by JonathanSum** [comment]
nvm, the line at the left portion is not totally flat.

**Comment by Atcold** [comment]
Haha, yes, you're correct.
The scale does not allow you to see the > 0 slope.

(I could not not laugh at reading your first message. Of course I mean no offense. Thanks for sending so many contributions! You're doing an exceptional job here! THANKS!)

**Comment by Atcold** [comment]
Please, keep opening issues regarding anything that is making little sense.
And for questions about the lessons, ask on YouTube.

Thank you for being an active student! ❤️
