### ISSUE TITLE
Duplicate image on 10-2.md

### ISSUE THREAD

**Issue by marcozullich** [Atcold/pytorch-Deep-Learning#413]
On `10-2.md` figures 4 and 5 are the same: namely, fig. 4 (predict step of ClusterFit) is repeated also in place of fig. 5, which should depict "Standard" pretrain + transfer vs. "Standard" pretrain + ClusterFit.
![immagine](https://user-images.githubusercontent.com/32547850/87854954-8b7de000-c915-11ea-9e28-00029fd178d7.png)

**Comment by Atcold** [comment]
Can you find the correct image from the [slides](https://drive.google.com/open?id=16lsnDN2HIBTcRucbVKY5B_U16c0tNQhR)?

**Comment by marcozullich** [comment]
Yep, it's the one on page 72/108.

**Comment by marcozullich** [comment]
![immagine](https://user-images.githubusercontent.com/32547850/87876721-643d1680-c9da-11ea-81e1-6d3d5f0f023b.png)

**Comment by Atcold** [comment]
Let me know if you can send a PR with the fix! 😊

**Comment by marcozullich** [comment]
Just 2 questions, so that I can be more independent in the future:
1) How can I upload images to the site?
2) Can I just take a screenshot of the image from the slides? No worries for quality / resolution?

**Comment by Atcold** [comment]
Yeah, for now there hasn't been any strict prescription.
You just want to push them to `docs/images/weekXX/XX-x/`.
