### ISSUE TITLE
Notation Issues in Week 5 Practicals Part 1

### ISSUE THREAD

**Issue by ankit-a-aggarwal** [Atcold/pytorch-Deep-Learning#460]
https://atcold.github.io/pytorch-Deep-Learning/en/week05/05-3/.
![image](https://user-images.githubusercontent.com/9767611/90425136-47553b00-e08d-11ea-9d1b-96dd84a159e1.png)
m here refers to the number of components in the output vector. (In the earlier lectures m referred to number of examples in the training set).
k refers to the number of components in vector of weights. The components of the vector of weights are the same in each row of the matrix, but they are different for stacked matrices. [(a11,a12,a13,0,0,0,0,...),(0,a11,a12,a13,0,0,0,0,....),....]. For each of the m stacked matrices, we will have a unique vector (each vector is of length k).

From the passage - 
1D convolution
We have 1 dimensional convolution going from 2 channels (stereophonic signal) to 16 channels (16 kernels) with kernel size of 3 and stride of 1. We then have 16 kernels with thickness 2 and length 3. Let’s assume that the input signal has a batch of size 1(one signal), 2 channels and 64 samples. The resulting output layer has 1 signal, 16 channels and the length of the signal is 62 (=64−3+1). Also, if we output the bias size, we’ll find the bias size is 16, since we have one bias per weight.

conv = nn.Conv1d(2, 16, 3)  # 1 Dimension 2 channels (stereo signal), 16 kernels of size 3

conv.weight.size()          # output: torch.Size([16, 2, 3]) . So the local receptive field is of size 3*2=6 different weights. These 6 weights are carried forward throughout the whole input signal. Then for each kernel which have a new set of 6 different weights to detect a new feature.

conv.bias.size()            # output: torch.Size([16])

x = torch.rand(1, 2, 64)    # batch of size 1, 2 channels, 64 samples
conv(x).size()              # output: torch.Size([1, 16, 62]) . So 16 different vectors, each of size 62.

conv = nn.Conv1d(2, 16, 5)  # 2 channels, 16 kernels of size 5
conv(x).size()              # output: torch.Size([1, 16, 60])

2D convolution
We first define the input data as 1 sample, 20 channels (say, we’re using an hyperspectral image) with height 64 and width 128. The 2D convolution has 20 channels from input and 16 kernels with size of 3*5. After the convolution, the output data has 1 sample, 16 channels with height 62 (=64−3+1) and width 124(=128−5+1).

x = torch.rand(1, 20, 64, 128)    # 1 sample, 20 channels, height 64, and width 128
conv = nn.Conv2d(20, 16, (3, 5))  # 20 channels, 16 kernels, kernel size is 3 x 5
conv.weight.size()                # output: torch.Size([16, 20, 3, 5])
conv(x).size()                    # output: torch.Size([1, 16, 62, 124])

How do you map 20 input channels to 16 output kernels?

**Comment by Atcold** [comment]
To map 20 input channels to 16 maps you want to use 16 kernels having channel size 20.
