### ISSUE TITLE
[AR]translation error

### ISSUE THREAD

**Issue by AliEl-01** [Atcold/pytorch-Deep-Learning#507]
in week03-2 (https://github.com/Atcold/pytorch-Deep-Learning/commit/caeda33cc0c622be8d690ecb104a20812afa6c6e) i fond that the "figures" under pictures aren't translated !!!

**Comment by JonathanSum** [comment]
Don't forget to put [JP] translation error if it is a Japanese translation error.

**Comment by ElJAZRY** [comment]
Done, thanks.

**Comment by AliEl-01** [comment]
I just checked out the docs 03-2 & I found the error there!!! Are you sure that you fixed it?
Sorry if you didn't understand what error I mean!

**Comment by AliEl-01** [comment]
![20200906_192755](https://user-images.githubusercontent.com/58257628/92332624-3e95ca80-f077-11ea-9eed-8d9cbdac2534.jpg)
I mean that one!!!

**Comment by ElJAZRY** [comment]
Yes, I edit it in my [fork](https://github.com/ElJAZRY/pytorch-Deep-Learning/blob/master/docs/ar/week03/03-2.md), it needs to be merged in the main repo.

**Comment by AliEl-01** [comment]
Oh okey Great

**Comment by Atcold** [comment]
Closing this issue, since it seems resolved.
