### ISSUE TITLE
Latex issue

### ISSUE THREAD

**Issue by JonathanSum** [Atcold/pytorch-Deep-Learning#510]
I have said this on Stack, but I deleted it and post it here because I guess I should post it here.

Latex issue:
![image](https://user-images.githubusercontent.com/21982975/92334250-27bf8b80-f017-11ea-9512-9d7489af155b.png)

And the Chinese version also has this problem too.
I don't know how to fix the Chinese version since the English version has this issue too.
![image](https://user-images.githubusercontent.com/21982975/92334256-3312b700-f017-11ea-9485-6ee34703622d.png)
Feel free to close it is a known issue.
Other: 
![image](https://user-images.githubusercontent.com/21982975/92372911-8bce6800-f088-11ea-8b31-d8034186ec96.png)

**Comment by Atcold** [comment]
@ebetica, can you have a look?
Stuff looks weird…

**Comment by JonathanSum** [comment]
![image](https://user-images.githubusercontent.com/21982975/93134343-97f78e00-f663-11ea-89e0-f4cff84de096.png)
neighborhood or neighbor? And there is a latex issue.

**Comment by JonathanSum** [comment]
I suggest it should be "which results in a hl+1 matrix with size of nxd.

**Comment by JonathanSum** [comment]
![image](https://user-images.githubusercontent.com/21982975/93136377-c3c84300-f666-11ea-91cc-3c6e3217c0ed.png)

**Comment by JonathanSum** [comment]
![image](https://user-images.githubusercontent.com/21982975/93139395-95993200-f66b-11ea-8101-877e9ab8e37d.png)
Sage or SAGE?
