### ISSUE TITLE
15-transformer. build_vocab function does not take the argument "specials"

### ISSUE THREAD

**Issue by JonathanSum** [Atcold/pytorch-Deep-Learning#524]
![image](https://user-images.githubusercontent.com/21982975/92521839-db0bba00-f1a8-11ea-9eae-ef963a707988.png)
It looks like the Field class has default UNK and PAD token in the __init__.

here is part of build_vocab that has the specails and its return statement:
```
        specials = list(OrderedDict.fromkeys(
            tok for tok in [self.unk_token, self.pad_token, self.init_token,
                            self.eos_token]
            if tok is not None))
        self.vocab = self.vocab_cls(counter, specials=specials, **kwargs)
```

**Comment by Atcold** [comment]
@ashkamath, do you understand what's going on here?

**Comment by ashkamath** [comment]
I dunno, maybe a version mismatch?

**Comment by JonathanSum** [comment]
I was using a Pytorch 1.6

**Comment by JonathanSum** [comment]
Is that because any of you were using a newer version?
Colab uses Pytorch 1.6.0+cu101

And Colab uses this torch text 

![image](https://user-images.githubusercontent.com/21982975/92996442-890fb080-f496-11ea-93b4-7e9b93e6ea25.png)

https://colab.research.google.com/drive/1OzNy272VtJlc_ABX8cPO0exJwNjWBKLK?usp=sharing

**Comment by Atcold** [comment]
Merged.
