### ISSUE TITLE
[Content] lecture note 14-2.md

### ISSUE THREAD

**Issue by marofmar** [Atcold/pytorch-Deep-Learning#526]
In the English lecture note 14-2.md, line 55

`A: Hinge is better than NLL becuase **hinge** will try to push the difference between the correct answer and other answers to infinity, whereas hinge only wants to make it larger than some value (the margin m). `

supposed to be changed into 

`A: Hinge is better than NLL becuase **NLL** will try to push the difference between the correct answer and other answers to infinity, whereas hinge only wants to make it larger than some value (the margin m). `

**Comment by Atcold** [comment]
Please, send a PR, and mention this issue in it.
