### ISSUE TITLE
Portuguese translation

### ISSUE THREAD

**Issue by ricardobarroslourenco** [Atcold/pytorch-Deep-Learning#53]
Hi @Atcold ! I would like to know how and where should I commit markdown files in Portuguese? I recall that you have commented something with @ebetica .

**Comment by ebetica** [comment]
It's not currently possible to switch between languages currently (maybe @Atcold and I had a miscommunication)... It's gonna take some time to design unfortunately, I'm not sure if there's a good interim solutions. Perhaps we can just put it into `docs/i18n/pt` for now?

I think based on how Gitbook does it, we should just have multiple directories that are unique right? So each language just has to have its own parallel site - therefore, if the English book is updated, it's not necessary for the other languages to be kept in sync.

**Comment by ricardobarroslourenco** [comment]
Perhaps I may get this on another `github.io` , and do some manual syncing with this repo, keeping the same licensing, but the content entirely in Portuguese.

**Comment by ebetica** [comment]
I think Alfredo wants it on the same website eventually. Maybe the new github.io is okay for now

**Comment by Atcold** [comment]
Hold on with the translation. We're still cleaning up the current submissions.
There will be soon an update from my side.

**Comment by Atcold** [comment]
I have a question, @ricardobarroslourenco.
Were you thinking to translate everything yourself, or organise a team of Portuguese speaking people?

**Comment by ricardobarroslourenco** [comment]
I'm thinking about translating myself, although open for people to join in.

**Comment by ebetica** [comment]
#69 adds support for multiple languages - you can simply put it in a new folder `/pt/*.md`, and add

```
lang: pt
lang-ref: ***
```

in the header. The lang-ref matches whatever page you're translating on the english side (feel free to add one if it doesn't exist)

**Comment by ricardobarroslourenco** [comment]
Thanks @ebetica . Going for edits this weekend :)

**Comment by Atcold** [comment]
@ricardobarroslourenco, do you  need any help from me?
We've started the Korean translation as well, now!

**Comment by ricardobarroslourenco** [comment]
@Atcold I'll look into the Korean work, just to see the organization dynamics.
I've been stuck in work because my company entered in Contingency due to COVID outbreak, and I'm helping them to put 60k employees to work fully remotely. I should be able to Start working on the weekend.

**Comment by Atcold** [comment]
If you shoot me an email, at my_surname @ nyu. edu, I can add you to the Slack channel.
Also, I have found other fellow Portuguese speakers who can help out.
