### ISSUE TITLE
[FR] missing title in week06

### ISSUE THREAD

**Issue by AliEl-01** [Atcold/pytorch-Deep-Learning#539]
the title (Batch-Ification in Language Modeling) is missing in (06-3.md)

**Comment by Atcold** [comment]
@lbourdois, send a PR when you can.
Have the commit message including `close #539` to automatically close this issue at merging time.

**Comment by Atcold** [comment]
Also, images and math are not showing up… 😕
The automatic translation utility used fucked up badly…

**Comment by lbourdois** [comment]
@AliEl-01 @Atcold 

Did I miss something? Because I don't understand what the problem is. The title is [there](https://github.com/Atcold/pytorch-Deep-Learning/blob/master/docs/fr/week06/06-3.md)

**Comment by lbourdois** [comment]
> Also, images and math are not showing up… 😕
> The automatic translation utility used fucked up badly…

@Atcold 
What appears on the site is my first PR (#502). The corrections you merged a few hours ago (#535) don't appear on the site (the files in the repo are correct). Is there a delay to wait to see the changes on the site  or is a new problem to solve :weary: ?

**Comment by AliEl-01** [comment]
Oh ok sorry I saw just the site page soo I declared this issue. I'm sorry again 🙏🏻
