### ISSUE TITLE
[IT] missing title in week06

### ISSUE THREAD

**Issue by AliEl-01** [Atcold/pytorch-Deep-Learning#540]
same issue in [FR] version. the title (Batch-Ification in Language Modeling) is missing in (06-3.md)

**Comment by Atcold** [comment]
I'm confused. I see it.

![image](https://user-images.githubusercontent.com/2119355/93027873-f7ab5600-f5dd-11ea-935d-bab6aa14454e.png)

**Comment by AliEl-01** [comment]
I'm sorry, I mean the Italian version, it's my fault!!!!

**Comment by AliEl-01** [comment]
![Uploading issue italy.PNG…]()

**Comment by AliEl-01** [comment]
sorry language confuse a little bit :(
![issue italy](https://user-images.githubusercontent.com/58257628/93030168-e7fd3300-f618-11ea-8bfd-906f44079a08.PNG)

**Comment by Atcold** [comment]
Thanks! There was missing a `>` after `</center`.
