### ISSUE TITLE
[AR] Arabic Translation Contribution.

### ISSUE THREAD

**Issue by Hasssan-Ramadan** [Atcold/pytorch-Deep-Learning#548]
How can I contribute to the course's translation to the Arabic version? I have searched a lot in the repo about the contribution page, but I can't get it.

**Comment by AliEl-01** [comment]
hi hassan ! how can i help ?

**Comment by Atcold** [comment]
Hi @Hasssan-Ramadan, please send me an email at Canziani @ NYU. edu
I'll add you to our Slack, and will tell you how to contribute.
In short, [here](https://github.com/Atcold/pytorch-Deep-Learning/wiki/Arabic-Translation) there's a list of missing chapters.
