### ISSUE TITLE
Latex issue

### ISSUE THREAD

**Issue by JonathanSum** [Atcold/pytorch-Deep-Learning#563]
![image](https://user-images.githubusercontent.com/21982975/93450190-9e068e00-f860-11ea-9031-cd802074c96f.png)

**Comment by Atcold** [comment]
What file is this?

**Comment by JonathanSum** [comment]
It should be either 13-2 or 13-3. In addition,  i dont see week 13 and 14's articles.

**Comment by Atcold** [comment]
One problem per issue, @JonathanSum, so that we can fix them all. Okay?

**Comment by JonathanSum** [comment]
@Atcold my bad.  You are right.
