### ISSUE TITLE
[AR] issue in docs/ar

### ISSUE THREAD

**Issue by AliEl-01** [Atcold/pytorch-Deep-Learning#564]
Hi @Atcold In my last PR I have organized week06 files in one folder! So.. please if you can delete 06.md^&^06-1.md from docs/ar , delete them please! Cuz there are already in week06 folder !
![20200917_121413.jpg](https://user-images.githubusercontent.com/58257628/93463714-09dc0b80-f8e0-11ea-90dc-6be964fc3c51.jpg)

**Comment by Atcold** [comment]
You can send a PR where you delete them.
