### ISSUE TITLE
[AR] 03-2.md (issue)

### ISSUE THREAD

**Issue by AliEl-01** [Atcold/pytorch-Deep-Learning#565]
@ElJAZRY I think there is something wrong in 03.2 page(https://atcold.github.io/pytorch-Deep-Learning/ar/week03/03-2/) ! Please check it and accept my apologies if everything okay🙏🏻.

**Comment by Atcold** [comment]
I don't understand Arabic.
Edit the file and send a PR. Add "Close #565" to the commit message to automatically close this issue.
