### ISSUE TITLE
res.plot_lib error

### ISSUE THREAD

**Issue by uysalserkan** [Atcold/pytorch-Deep-Learning#674]
Hi,
I installed res module on pip / conda but when I want to import this `from res.plot_lib import set_default, show_scatterplot, plot_bases` line, attached error occur.
How can I solve this error?
![Screenshot 2020-10-18 183353](https://user-images.githubusercontent.com/24881389/96372708-cd1a6300-1170-11eb-8bb9-8628d9d58767.png)

**Comment by Albmargar1** [comment]
"res.plot_lib" is a custom library and it's located in this repository. Probably "pip install res" will be a different package.

**Comment by uysalserkan** [comment]
Upss. I'm sorry. Thanks <3

**Comment by Atcold** [comment]
Yeah, I've simply hid some plotting code into a `res`-ources folder.
