### ISSUE TITLE
13-1 Typo in the definition of convolution

### ISSUE THREAD

**Issue by snjot** [Atcold/pytorch-Deep-Learning#678]
There is a minor typo of the definition of convolution in `week13/13-1.md` . It seems to me that the superscript of `h` should be `l+1`, not `l_1` .

- https://github.com/Atcold/pytorch-Deep-Learning/blob/master/docs/en/week13/13-1.md#how-do-we-define-convolution

| line | read | should read|
| --- | --- | --- |
| [150](https://github.com/Atcold/pytorch-Deep-Learning/blob/a89dce7181e59ca81865e50d95c1508141864b70/docs/en/week13/13-1.md#how-do-we-define-convolution)  | `$$h_i^{\ell_1} = w^\ell * h_i^\ell$$` | `$$h_i^{\ell+1} = w^\ell * h_i^\ell$$` |

This typo is also found in other language versions.

See also:
- https://youtu.be/Iiv9R6BjxHM?t=958

**Comment by Atcold** [comment]
Yes, of course, you're correct. Can you fix all versions? Thanks!

**Comment by snjot** [comment]
Merged (#688)

**Comment by Atcold** [comment]
Sweet, great!
