### ISSUE TITLE
Errata in 02-space_stetching.ipynb?

### ISSUE THREAD

**Issue by rightx2** [Atcold/pytorch-Deep-Learning#684]
In the code of applying SVD, I think `new_OI = OI @ W` is supposed to be `new_OI = OI @ W.t()`?

**Comment by Atcold** [comment]
Yeah, it's likely. Can you fix it?

**Comment by rightx2** [comment]
@Atcold I've sent PR!

**Comment by Atcold** [comment]
Great, thanks!
