### ISSUE TITLE
Equation in 01-3.md doesn't render

### ISSUE THREAD

**Issue by titusjgr** [Atcold/pytorch-Deep-Learning#75]
The Katex code in [the markdown file of 01-3](https://github.com/Atcold/pytorch-Deep-Learning/blob/master/docs/chapters/01-3.md) doesn't render.
```
$$
\label{nonlinear_transform}
    f(x) = tanh\bigg(\begin{bmatrix} s & 0 \\ 0 & s \end{bmatrix} \bigg)
$$
```

**Comment by ebetica** [comment]
Should work if you get rid of the `\label` line.

**Comment by Atcold** [comment]
Any update, @titusjgr?

**Comment by titusjgr** [comment]
What was the `\label` line for?

**Comment by ebetica** [comment]
In Latex, it's so you can `\ref{label_name}` in a future section, but I don't see it used anywhere else so the student probably just inserted it by mistake.

**Comment by titusjgr** [comment]
Some lines are referencing equations using numbers.  Should I manually `\tag` those referenced?

**Comment by Atcold** [comment]
I confirm that removing the label and adding one empty line before and after the equation gets the equation rendered.
So, just go with what currently is done in `01-3.md`.
