### ISSUE TITLE
farsi links don't work

### ISSUE THREAD

**Issue by kooshiar** [Atcold/pytorch-Deep-Learning#760]
The problem is with the url
if you replace /fa/en with /en it goes to the english version
couldn't find the right url for the farsi lectures

<img width="1032" alt="Screen Shot 2021-02-08 at 11 06 52 AM" src="https://user-images.githubusercontent.com/3936730/107269300-41b62d80-69fe-11eb-8377-eef128affae2.png">

**Comment by kooshiar** [comment]
now if you replace /fa/en with /fa you go to farsi pages
if you fix the links in the homepage everything is good to go

**Comment by Atcold** [comment]
This seems to have been already fixed.
