### ISSUE TITLE
RuntimeError: a view of a leaf Variable that requires grad is being used in an in-place operation.

### ISSUE THREAD

**Issue by nadiagit** [Atcold/pytorch-Deep-Learning#765]
Edit: Thus far I've found [here](https://discuss.pytorch.org/t/leaf-variable-was-used-in-an-inplace-operation/308/2) that we can clone the leaf variable or use torch.no_grad 
What will be the intuition behind using clone or torch.no_grad? 
Is it correct to use torch.no_grad, as the position encoding is what we compute and give the model? And is not learned. 

Hi, I have a runtime error and I can't figure out why 😅 

when I run
```
model = TransformerClassifier(num_layers=1, d_model=32, num_heads=2, 
                         conv_hidden_dim=128, input_vocab_size=50002, num_answers=2)
```

I get the following error 

```
----> 6     E[:, 0::2] = torch.FloatTensor(np.sin(theta[:, 0::2]))
RuntimeError: a view of a leaf Variable that requires grad is being used in an in-place operation.
```

Thanks for any ideas 🌞

**Comment by Atcold** [comment]
I think you may need to update your PyTorch. I don't see this issue using the virtual environment we provide.
