### ISSUE TITLE
Cannote create pDL environment

### ISSUE THREAD

**Issue by jcatanza** [Atcold/pytorch-Deep-Learning#770]
On my 64-bit Windows 10 machine, the command 

conda env create -f environment.yml 

throws the following error: 

ERROR conda.core.link:_execute(698): An error occurred while installing package 'conda-forge::cudatoolkit-11.0.3-h3f58a73_8'

Can anyone who has encountered and solved this problem provide the fix?

See below for details
===========================
(base) PS C:\Users\cross-entropy\cloned_git_repos> cd .\nyu-dl-pytorch\
(base) PS C:\Users\cross-entropy\cloned_git_repos\nyu-dl-pytorch> git pull
Already up to date.
(base) PS C:\Users\cross-entropy\cloned_git_repos\nyu-dl-pytorch> ls

    Directory: C:\Users\cross-entropy\cloned_git_repos\nyu-dl-pytorch

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         3/27/2021  10:32 AM                .ipynb_checkpoints
d-----         3/27/2021  10:27 AM                docs
d-----         3/27/2021  10:27 AM                extra
d-----         3/27/2021  10:27 AM                res
d-----         3/27/2021  10:27 AM                slides
-a----         3/27/2021  10:27 AM            278 .gitignore
-a----         3/27/2021  10:27 AM             97 .gitmodules
-a----         3/27/2021  10:27 AM           9202 00-logic_neuron_programming.ipynb
-a----         3/27/2021  10:27 AM          19708 01-tensor_tutorial.ipynb
-a----         3/27/2021  10:27 AM           7008 02-space_stretching.ipynb
-a----         3/27/2021  10:27 AM           7159 03-autograd_tutorial.ipynb
-a----         3/27/2021  10:27 AM           7719 04-spiral_classification.ipynb
-a----         3/27/2021  10:27 AM           9909 05-regression.ipynb
-a----         3/27/2021  10:27 AM          14370 06-convnet.ipynb
-a----         3/27/2021  10:27 AM           9115 07-listening_to_kernels.ipynb
-a----         3/27/2021  10:27 AM          24406 08-seq_classification.ipynb
-a----         3/27/2021  10:27 AM           7586 09-echo_data.ipynb
-a----         3/27/2021  10:27 AM           7737 10-autoencoder.ipynb
-a----         3/27/2021  10:27 AM          10672 11-VAE.ipynb
-a----         3/27/2021  10:27 AM          20118 12-regularization.ipynb
-a----         3/27/2021  10:27 AM           4674 13-bayesian_nn.ipynb
-a----         3/27/2021  10:27 AM          13547 14-truck_backer-upper.ipynb
-a----         3/27/2021  10:27 AM          26758 15-transformer.ipynb
-a----         3/27/2021  10:27 AM         618659 16-gated_GCN.ipynb
-a----         3/27/2021  10:27 AM             17 apt.txt
-a----         3/27/2021  10:27 AM            294 environment.yml
-a----         3/27/2021  10:27 AM            285 LICENSE.md
-a----         3/27/2021  10:27 AM           3828 README.md

(base) PS C:\Users\cross-entropy\cloned_git_repos\nyu-dl-pytorch> conda env create -f environment.yml
Collecting package metadata (repodata.json): done
Solving environment: done

Downloading and Extracting Packages
m2w64-gcc-libgfortra | 342 KB    | ##################################################################################################################################################################### | 100%
pyqtwebengine-5.12.1 | 143 KB    | ##################################################################################################################################################################### | 100%
libclang-11.1.0      | 20.8 MB   | ##################################################################################################################################################################### | 100%
setuptools-49.6.0    | 962 KB    | ##################################################################################################################################################################### | 100%
entrypoints-0.3      | 8 KB      | ##################################################################################################################################################################### | 100%
six-1.15.0           | 14 KB     | ##################################################################################################################################################################### | 100%
ca-certificates-2020 | 173 KB    | ##################################################################################################################################################################### | 100%
colorama-0.4.4       | 18 KB     | ##################################################################################################################################################################### | 100%
pywin32-300          | 7.0 MB    | ##################################################################################################################################################################### | 100%
pandocfilters-1.4.2  | 9 KB      | ##################################################################################################################################################################### | 100%
pickleshare-0.7.5    | 9 KB      | ##################################################################################################################################################################### | 100%
pyqt-5.12.3          | 22 KB     | ##################################################################################################################################################################### | 100%
prompt-toolkit-3.0.1 | 244 KB    | ##################################################################################################################################################################### | 100%
importlib-metadata-3 | 27 KB     | ##################################################################################################################################################################### | 100%
torchtext-0.8.0      | 2.9 MB    | ##################################################################################################################################################################### | 100%
qt-5.12.9            | 106.1 MB  | ##################################################################################################################################################################### | 100%
python_abi-3.8       | 4 KB      | ##################################################################################################################################################################### | 100%
threadpoolctl-2.1.0  | 15 KB     | ##################################################################################################################################################################### | 100%
pytorch-1.7.0        | 1003.4 MB | ##################################################################################################################################################################### | 100%
prompt_toolkit-3.0.1 | 4 KB      | ##################################################################################################################################################################### | 100%
backports-1.0        | 4 KB      | ##################################################################################################################################################################### | 100%
opencv-4.5.1         | 22 KB     | ##################################################################################################################################################################### | 100%
notebook-6.3.0       | 7.6 MB    | ##################################################################################################################################################################### | 100%
nest-asyncio-1.5.1   | 9 KB      | ##################################################################################################################################################################### | 100%
send2trash-1.5.0     | 12 KB     | ##################################################################################################################################################################### | 100%
pysocks-1.7.1        | 28 KB     | ##################################################################################################################################################################### | 100%
pyopenssl-20.0.1     | 48 KB     | ##################################################################################################################################################################### | 100%
pandoc-2.13          | 16.3 MB   | ##################################################################################################################################################################### | 100%
webencodings-0.5.1   | 12 KB     | ##################################################################################################################################################################### | 100%
idna-2.10            | 52 KB     | ##################################################################################################################################################################### | 100%
pyqt5-sip-4.19.18    | 298 KB    | ##################################################################################################################################################################### | 100%
nbconvert-6.0.7      | 568 KB    | ##################################################################################################################################################################### | 100%
xz-5.2.5             | 211 KB    | ##################################################################################################################################################################### | 100%
ipywidgets-7.6.3     | 101 KB    | ##################################################################################################################################################################### | 100%
freeglut-3.2.1       | 149 KB    | ##################################################################################################################################################################### | 100%
markupsafe-1.1.1     | 30 KB     | ##################################################################################################################################################################### | 100%
jinja2-2.11.3        | 93 KB     | ##################################################################################################################################################################### | 100%
ipython_genutils-0.2 | 21 KB     | ##################################################################################################################################################################### | 100%
nb_conda_kernels-2.3 | 27 KB     | ##################################################################################################################################################################### | 100%
tk-8.6.10            | 3.2 MB    | ##################################################################################################################################################################### | 100%
lcms2-2.12           | 882 KB    | ##################################################################################################################################################################### | 100%
networkx-2.5         | 1.2 MB    | ##################################################################################################################################################################### | 100%
pysoundfile-0.10.3.p | 23 KB     | ##################################################################################################################################################################### | 100%
testpath-0.4.4       | 85 KB     | ##################################################################################################################################################################### | 100%
zstd-1.4.9           | 915 KB    | ##################################################################################################################################################################### | 100%
libsodium-1.0.18     | 697 KB    | ##################################################################################################################################################################### | 100%
audioread-2.1.9      | 33 KB     | ##################################################################################################################################################################### | 100%
pyrsistent-0.17.3    | 92 KB     | ##################################################################################################################################################################### | 100%
llvmlite-0.36.0      | 15.1 MB   | ##################################################################################################################################################################### | 100%
pillow-8.1.2         | 774 KB    | ##################################################################################################################################################################### | 100%
libpng-1.6.37        | 724 KB    | ##################################################################################################################################################################### | 100%
winpty-0.4.3         | 1.1 MB    | ##################################################################################################################################################################### | 100%
jupyter_console-6.4. | 22 KB     | ##################################################################################################################################################################### | 100%
matplotlib-3.4.1     | 7 KB      | ##################################################################################################################################################################### | 100%
win_inet_pton-1.1.0  | 8 KB      | ##################################################################################################################################################################### | 100%
blas-2.108           | 13 KB     | ##################################################################################################################################################################### | 100%
libsndfile-1.0.31    | 354 KB    | ##################################################################################################################################################################### | 100%
pyqt-impl-5.12.3     | 4.3 MB    | ##################################################################################################################################################################### | 100%
backports.functools_ | 9 KB      | ##################################################################################################################################################################### | 100%
python-dateutil-2.8. | 220 KB    | ##################################################################################################################################################################### | 100%
pywinpty-0.5.7       | 51 KB     | ##################################################################################################################################################################### | 100%
libprotobuf-3.15.7   | 2.3 MB    | ##################################################################################################################################################################### | 100%
decorator-5.0.4      | 11 KB     | ##################################################################################################################################################################### | 100%
jupyterlab-3.0.12    | 5.6 MB    | ##################################################################################################################################################################### | 100%
libblas-3.9.0        | 3.9 MB    | ##################################################################################################################################################################### | 100%
wcwidth-0.2.5        | 33 KB     | ##################################################################################################################################################################### | 100%
py-opencv-4.5.1      | 23 KB     | ##################################################################################################################################################################### | 100%
backcall-0.2.0       | 13 KB     | ##################################################################################################################################################################### | 100%
wincertstore-0.2     | 15 KB     | ##################################################################################################################################################################### | 100%
cryptography-3.4.7   | 706 KB    | ##################################################################################################################################################################### | 100%
pyqtchart-5.12       | 212 KB    | ##################################################################################################################################################################### | 100%
babel-2.9.0          | 6.2 MB    | ##################################################################################################################################################################### | 100%
pygments-2.8.1       | 736 KB    | ##################################################################################################################################################################### | 100%
attrs-20.3.0         | 41 KB     | ##################################################################################################################################################################### | 100%
jedi-0.18.0          | 931 KB    | ##################################################################################################################################################################### | 100%
libflac-1.3.3        | 324 KB    | ##################################################################################################################################################################### | 100%
mkl-2020.4           | 172.4 MB  | ##################################################################################################################################################################### | 100%
liblapack-3.9.0      | 3.9 MB    | ##################################################################################################################################################################### | 100%
sniffio-1.2.0        | 15 KB     | ##################################################################################################################################################################### | 100%
terminado-0.9.4      | 26 KB     | ##################################################################################################################################################################### | 100%
olefile-0.46         | 32 KB     | ##################################################################################################################################################################### | 100%
nbclassic-0.2.6      | 17 KB     | ##################################################################################################################################################################### | 100%
pytz-2021.1          | 239 KB    | ##################################################################################################################################################################### | 100%
blas-devel-3.9.0     | 12 KB     | ##################################################################################################################################################################### | 100%
tornado-6.1          | 649 KB    | ##################################################################################################################################################################### | 100%
parso-0.8.2          | 68 KB     | ##################################################################################################################################################################### | 100%
m2w64-gcc-libs-core- | 214 KB    | ##################################################################################################################################################################### | 100%
resampy-0.2.2        | 332 KB    | ##################################################################################################################################################################### | 100%
freetype-2.10.4      | 489 KB    | ##################################################################################################################################################################### | 100%
jupyter_server-1.5.1 | 424 KB    | ##################################################################################################################################################################### | 100%
jupyter-1.0.0        | 6 KB      | ##################################################################################################################################################################### | 100%
traitlets-5.0.5      | 81 KB     | ##################################################################################################################################################################### | 100%
wheel-0.36.2         | 31 KB     | ##################################################################################################################################################################### | 100%
librosa-0.8.0        | 145 KB    | ##################################################################################################################################################################### | 100%
cffi-1.14.5          | 228 KB    | ##################################################################################################################################################################### | 100%
torchvision-0.8.1    | 7.2 MB    | ##################################################################################################################################################################### | 100%
pooch-1.3.0          | 40 KB     | ##################################################################################################################################################################### | 100%
widgetsnbextension-3 | 1.8 MB    | ##################################################################################################################################################################### | 100%
mkl-include-2020.4   | 696 KB    | ##################################################################################################################################################################### | 100%
joblib-1.0.1         | 206 KB    | ##################################################################################################################################################################### | 100%
numba-0.53.1         | 3.7 MB    | ##################################################################################################################################################################### | 100%
libopus-1.3.1        | 255 KB    | ##################################################################################################################################################################### | 100%
sqlite-3.35.3        | 1.2 MB    | ##################################################################################################################################################################### | 100%
m2w64-gcc-libs-5.3.0 | 520 KB    | ##################################################################################################################################################################### | 100%
msys2-conda-epoch-20 | 3 KB      | ##################################################################################################################################################################### | 100%
qtpy-1.9.0           | 34 KB     | ##################################################################################################################################################################### | 100%
m2w64-libwinpthread- | 31 KB     | ##################################################################################################################################################################### | 100%
cycler-0.10.0        | 9 KB      | ##################################################################################################################################################################### | 100%
argon2-cffi-20.1.0   | 51 KB     | ##################################################################################################################################################################### | 100%
json5-0.9.5          | 20 KB     | ##################################################################################################################################################################### | 100%
certifi-2020.12.5    | 144 KB    | ##################################################################################################################################################################### | 100%
chardet-4.0.0        | 224 KB    | ##################################################################################################################################################################### | 100%
zlib-1.2.11          | 126 KB    | ##################################################################################################################################################################### | 100%
pyzmq-22.0.3         | 700 KB    | ##################################################################################################################################################################### | 100%
mkl-devel-2020.4     | 5.6 MB    | ##################################################################################################################################################################### | 100%
zipp-3.4.1           | 11 KB     | ##################################################################################################################################################################### | 100%
typing_extensions-3. | 25 KB     | ##################################################################################################################################################################### | 100%
jupyterlab_pygments- | 8 KB      | ##################################################################################################################################################################### | 100%
ipykernel-5.5.3      | 168 KB    | ##################################################################################################################################################################### | 100%
scikit-learn-0.24.1  | 6.5 MB    | ##################################################################################################################################################################### | 100%
qtconsole-5.0.3      | 89 KB     | ##################################################################################################################################################################### | 100%
dgl-0.6.0post1       | 3.0 MB    | ##################################################################################################################################################################### | 100%
tqdm-4.59.0          | 77 KB     | ##################################################################################################################################################################### | 100%
python-3.8.8         | 19.2 MB   | ##################################################################################################################################################################### | 100%
requests-2.25.1      | 51 KB     | ##################################################################################################################################################################### | 100%
pycparser-2.20       | 94 KB     | ##################################################################################################################################################################### | 100%
vc-14.2              | 13 KB     | ##################################################################################################################################################################### | 100%
libopencv-4.5.1      | 45.9 MB   | ##################################################################################################################################################################### | 100%
mistune-0.8.4        | 54 KB     | ##################################################################################################################################################################### | 100%
matplotlib-base-3.4. | 7.3 MB    | ##################################################################################################################################################################### | 100%
ninja-1.10.2         | 273 KB    | ##################################################################################################################################################################### | 100%
pip-21.0.1           | 1.1 MB    | ##################################################################################################################################################################### | 100%
packaging-20.9       | 35 KB     | ##################################################################################################################################################################### | 100%
nbformat-5.1.3       | 47 KB     | ##################################################################################################################################################################### | 100%
vs2015_runtime-14.28 | 2.3 MB    | ##################################################################################################################################################################### | 100%
jpeg-9d              | 366 KB    | ##################################################################################################################################################################### | 100%
async_generator-1.10 | 18 KB     | ##################################################################################################################################################################### | 100%
cudatoolkit-11.0.3   | 942.7 MB  | ##################################################################################################################################################################### | 100%
appdirs-1.4.4        | 13 KB     | ##################################################################################################################################################################### | 100%
libvorbis-1.3.7      | 267 KB    | ##################################################################################################################################################################### | 100%
bleach-3.3.0         | 111 KB    | ##################################################################################################################################################################### | 100%
libcblas-3.9.0       | 3.9 MB    | ##################################################################################################################################################################### | 100%
jupyter_client-6.1.1 | 79 KB     | ##################################################################################################################################################################### | 100%
jsonschema-3.2.0     | 45 KB     | ##################################################################################################################################################################### | 100%
numpy-1.20.2         | 5.3 MB    | ##################################################################################################################################################################### | 100%
jupyter-packaging-0. | 13 KB     | ##################################################################################################################################################################### | 100%
intel-openmp-2020.3  | 2.0 MB    | ##################################################################################################################################################################### | 100%
anyio-2.2.0          | 116 KB    | ##################################################################################################################################################################### | 100%
libwebp-base-1.2.0   | 389 KB    | ##################################################################################################################################################################### | 100%
kiwisolver-1.3.1     | 58 KB     | ##################################################################################################################################################################### | 100%
zeromq-4.3.4         | 9.0 MB    | ##################################################################################################################################################################### | 100%
libtiff-4.2.0        | 1.1 MB    | ##################################################################################################################################################################### | 100%
libogg-1.3.4         | 34 KB     | ##################################################################################################################################################################### | 100%
scipy-1.6.2          | 23.3 MB   | ##################################################################################################################################################################### | 100%
urllib3-1.26.4       | 99 KB     | ##################################################################################################################################################################### | 100%
nbclient-0.5.3       | 67 KB     | ##################################################################################################################################################################### | 100%
defusedxml-0.7.1     | 23 KB     | ##################################################################################################################################################################### | 100%
openssl-1.1.1k       | 5.7 MB    | ##################################################################################################################################################################### | 100%
jupyter_core-4.7.1   | 96 KB     | ##################################################################################################################################################################### | 100%
m2w64-gmp-6.1.0      | 726 KB    | ##################################################################################################################################################################### | 100%
brotlipy-0.7.0       | 368 KB    | ##################################################################################################################################################################### | 100%
libuv-1.41.0         | 341 KB    | ##################################################################################################################################################################### | 100%
jasper-2.0.14        | 662 KB    | ##################################################################################################################################################################### | 100%
icu-68.1             | 16.3 MB   | ##################################################################################################################################################################### | 100%
jupyterlab_widgets-1 | 130 KB    | ##################################################################################################################################################################### | 100%
pyparsing-2.4.7      | 60 KB     | ##################################################################################################################################################################### | 100%
jupyterlab_server-2. | 36 KB     | ##################################################################################################################################################################### | 100%
liblapacke-3.9.0     | 3.9 MB    | ##################################################################################################################################################################### | 100%
prometheus_client-0. | 46 KB     | ##################################################################################################################################################################### | 100%
ipython-7.22.0       | 1.1 MB    | ##################################################################################################################################################################### | 100%
lz4-c-1.9.3          | 134 KB    | ##################################################################################################################################################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: | "By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions of the CUDA End User License Agreement (EULA): https://docs.nvidia.com/cuda/eula/index.html"

- Enabling nb_conda_kernels...
CONDA_PREFIX: C:\Users\cross-entropy\anaconda3\envs\pDL
Status: enabled

| Config option `kernel_spec_manager_class` not recognized by `EnableNBExtensionApp`.
Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: ok

done
ERROR conda.core.link:_execute(698): An error occurred while installing package 'conda-forge::cudatoolkit-11.0.3-h3f58a73_8'.
Rolling back transaction: done

LinkError: post-link script failed for package conda-forge::cudatoolkit-11.0.3-h3f58a73_8
location of failed script: C:\Users\cross-entropy\anaconda3\envs\pDL\Scripts\.cudatoolkit-post-link.bat
==> script messages <==
"By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions of the CUDA End User License Agreement (EULA): https://docs.nvidia.com/cuda/eula/index.html"

==> script output <==
stdout:
stderr: 'chcp' is not recognized as an internal or external command,
operable program or batch file.
'chcp' is not recognized as an internal or external command,
operable program or batch file.
'chcp' is not recognized as an internal or external command,
operable program or batch file.

return code: 1

()

**Comment by Atcold** [comment]
I don't unse Windows. This seems to be a [`conda-forge`](https://github.com/conda-forge/cudatoolkit-dev-feedstock/issues/9) issue. I suggest asking for help there.
