### ISSUE TITLE
Request to contribute the derivation of KL Divergence for two gaussian distributions

### ISSUE THREAD

**Issue by faizankshaikh** [Atcold/pytorch-Deep-Learning#806]
Hello @Atcold sir! 

I recently watched your video on VAEs and was motivated to derive the KL divergence for two gaussian distributions. I hope it will be useful for the rest. Here's the link to the [gist](https://gist.github.com/faizankshaikh/9800e3cc86dcff315a582eee0b59b652). It probably needs more refining - do let me know what can be improved.

**Comment by Atcold** [comment]
Thanks for the pointer!
