### ISSUE TITLE
week 6, ch 6.3

### ISSUE THREAD

**Issue by p-mishra1** [Atcold/pytorch-Deep-Learning#817]
![image](https://user-images.githubusercontent.com/87666586/157692366-5265f833-db5a-4784-be86-64e5bd571284.png)

The equation and the image do not support each other, in the image the input x[t-1] should be x[t] as mentioned in the equation @Atcold .

**Comment by p-mishra1** [comment]
yes exactly the equation is correct in the model diagram both the hidden state as well as the input are of same time stamp 
`h[t] = g(h[t-1], x[t-1])` this is what is mentioned in the model diagram.
am i missing something here?

**Comment by Atcold** [comment]
I see. The `h[t-1]`, `h[t]`, and `h[t+1]` should be ‘inside’ the circle, but they don't fit, so they are placed outside.
Last year I drew a better version of this diagram.

![image](https://user-images.githubusercontent.com/2119355/165386008-e92fc345-ee44-4cec-889d-850a6fcb842b.png)

You can see the full tweet [here](https://twitter.com/alfcnz/status/1447808331716907008).
