### ISSUE TITLE
[DLSP22]16-gated_GCN.ipynb in cell # 15, it should be batch_X and batch_E

### ISSUE THREAD

**Issue by lcqsigi** [Atcold/pytorch-Deep-Learning#820]
![batch_x_e](https://user-images.githubusercontent.com/30908505/164562351-a28d0231-7091-40ec-aeaa-5d9d12eeb913.PNG)

batch_scores = model(batch_graphs, **batch_X, batch_E**, batch_snorm_n, batch_snorm_e)
print(batch_scores.size())

batch_labels = batch_labels
print(f'accuracy: {accuracy(batch_scores, batch_labels)}')

torch.Size([10, 8])
accuracy: 10

**Comment by lcqsigi** [comment]
Upon running this notebook (i.e., `16-gated_GCN.ipynb`) with python version `3.9.7`, torch version `1.10.2`,  jupyter-notebook version `6.4.5`, and dgl version `0.6.0`, cell # 15 of the notebook prints: `NameError: name 'batch_x' is not defined`. If one replaces, the `batch_scores` definition with `batch_X` and `batch_E` in cell # 15 of the original `16-gated_GCN.ipynb` notebook, the notebook runs to completion reporting a `test_acc: 0.9900` after 40 Epochs.

**Comment by Atcold** [comment]
Oh, oh, I see, it's just a typo you fixed in #821.
Cool, thanks.
