### ISSUE TITLE
Week 5: Lab

### ISSUE THREAD

**Issue by SohamTamba** [Atcold/pytorch-Deep-Learning#96]
In the notes for week 5 lab,
the 2nd paragraph says: "Instead of using the matrix A above, we will change the matrix width to the kernel size k."
There is no matrix A mentioned above the paragraph.
I think it refering to the notes of a previous session.

**Comment by Atcold** [comment]
Right.
They did copy and paste what we covered the previous week, and I asked to remove.
I guess they have not fixed the content.
Can you plz fix it such that is readable?
You can either define `A` or refer to the previous week, or both.

**Comment by Atcold** [comment]
Perhaps @wtao0221 can help out, since s/he was the reviewer for that segment.

**Comment by wtao0221** [comment]
Yes. This is the overlapping part between this lab and previous one. So Alfredo recommends to delete that part and just refer to previous week. A new pull request is submitted. Thanks @Atcold
